### ISSUE TITLE
Show expires_in in example in README

### ISSUE THREAD

**Issue by martellaj** [hallipr/passport-vso#1]
Not sure how much this is actively being developed, but I've found it super useful while developing an app with the VSO API. Anyway, a suggestion I have is changing the example in the README to show the `params` parameter in the callback for `passport.use` since that's where the `expires_in` parameter is exposed in. Took a little bit of digging through the source to figure that out.

**Comment by hallipr** [comment]
I updated the readme with info from the OAuuth2 strategy docs.

**Comment by ivan-marquez** [comment]
Hi @hallipr,

How can I refresh the `accessToken`  using this strategy? Thanks!!
